import type { MigrationInterface, QueryRunner } from 'typeorm';

export class AuthSessions1789257600000 implements MigrationInterface {
  name = 'AuthSessions1789257600000';

  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      'ALTER TABLE users ADD COLUMN IF NOT EXISTS google_sub varchar',
    );
    await queryRunner.query(
      'CREATE UNIQUE INDEX IF NOT EXISTS uq_users_google_sub ON users (google_sub)',
    );
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS auth_sessions (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        public_id uuid NOT NULL,
        user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        image_url text,
        refresh_token_hash varchar(64) NOT NULL,
        expires_at timestamptz NOT NULL,
        revoked_at timestamptz,
        created_at timestamptz NOT NULL DEFAULT now()
      )
    `);
    await queryRunner.query(
      'CREATE UNIQUE INDEX IF NOT EXISTS uq_auth_sessions_public_id ON auth_sessions (public_id)',
    );
    await queryRunner.query(
      'CREATE INDEX IF NOT EXISTS idx_auth_sessions_user_id ON auth_sessions (user_id)',
    );
    await queryRunner.query(
      'CREATE INDEX IF NOT EXISTS idx_auth_sessions_expires_at ON auth_sessions (expires_at)',
    );
  }

  async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('DROP TABLE IF EXISTS auth_sessions');
    await queryRunner.query('DROP INDEX IF EXISTS uq_users_google_sub');
    await queryRunner.query(
      'ALTER TABLE users DROP COLUMN IF EXISTS google_sub',
    );
  }
}
