import type { MigrationInterface, QueryRunner } from 'typeorm';

/** Incremental migration. Down removes rental history; restore a backup to recover it. */
export class CreateRentalReservations1791146000000 implements MigrationInterface {
  name = 'CreateRentalReservations1791146000000';
  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query("-- SQL dump generated using DBML (dbml.dbdiagram.io)\n-- Database: PostgreSQL\n-- Generated at: 2026-10-04T20:51:25.156Z\n\n\nCREATE TABLE \"rental_properties\" (\n  \"id\" BIGSERIAL PRIMARY KEY NOT NULL,\n  \"owner_id\" bigint NOT NULL,\n  \"name\" varchar(255) NOT NULL,\n  \"location\" varchar(500),\n  \"timezone\" varchar(64) NOT NULL,\n  \"max_guests\" integer NOT NULL,\n  \"check_in_time\" time NOT NULL,\n  \"check_out_time\" time NOT NULL,\n  \"default_nightly_rate\" bigint,\n  \"default_deposit_percent\" numeric(5,2),\n  \"minimum_turnover_minutes\" integer NOT NULL DEFAULT 0,\n  \"default_cancellation_policy_id\" bigint,\n  \"notes\" text,\n  \"is_active\" boolean NOT NULL DEFAULT true,\n  \"created_by\" bigint NOT NULL,\n  \"updated_by\" bigint NOT NULL,\n  \"created_at\" timestamptz NOT NULL DEFAULT now(),\n  \"updated_at\" timestamptz NOT NULL DEFAULT now()\n)");
    await queryRunner.query("CREATE TABLE \"rental_collaborators\" (\n  \"id\" BIGSERIAL PRIMARY KEY NOT NULL,\n  \"property_id\" bigint NOT NULL,\n  \"user_id\" bigint NOT NULL,\n  \"position\" varchar(255),\n  \"is_active\" boolean NOT NULL DEFAULT true,\n  \"created_by\" bigint NOT NULL,\n  \"updated_by\" bigint NOT NULL,\n  \"created_at\" timestamptz NOT NULL DEFAULT now(),\n  \"updated_at\" timestamptz NOT NULL DEFAULT now()\n)");
    await queryRunner.query("CREATE TABLE \"rental_cancellation_policies\" (\n  \"id\" BIGSERIAL PRIMARY KEY NOT NULL,\n  \"property_id\" bigint NOT NULL,\n  \"name\" varchar(255) NOT NULL,\n  \"is_active\" boolean NOT NULL DEFAULT true,\n  \"created_by\" bigint NOT NULL,\n  \"updated_by\" bigint NOT NULL,\n  \"created_at\" timestamptz NOT NULL DEFAULT now(),\n  \"updated_at\" timestamptz NOT NULL DEFAULT now()\n)");
    await queryRunner.query("CREATE TABLE \"rental_cancellation_rules\" (\n  \"id\" BIGSERIAL PRIMARY KEY NOT NULL,\n  \"policy_id\" bigint NOT NULL,\n  \"min_days_before\" integer NOT NULL,\n  \"refund_percent\" numeric(5,2) NOT NULL,\n  \"created_by\" bigint NOT NULL,\n  \"updated_by\" bigint NOT NULL,\n  \"created_at\" timestamptz NOT NULL DEFAULT now(),\n  \"updated_at\" timestamptz NOT NULL DEFAULT now()\n)");
    await queryRunner.query("CREATE TABLE \"rental_reservations\" (\n  \"id\" BIGSERIAL PRIMARY KEY NOT NULL,\n  \"property_id\" bigint NOT NULL,\n  \"guest_name\" varchar(255) NOT NULL,\n  \"guest_contact\" varchar(255) NOT NULL,\n  \"guests_count\" integer NOT NULL,\n  \"channel\" varchar(32) NOT NULL,\n  \"external_reference\" varchar(255),\n  \"check_in_on\" date NOT NULL,\n  \"check_out_on\" date NOT NULL,\n  \"check_in_time\" time NOT NULL,\n  \"check_out_time\" time NOT NULL,\n  \"nightly_rate\" bigint NOT NULL,\n  \"cleaning_fee\" bigint NOT NULL DEFAULT 0,\n  \"discount_amount\" bigint NOT NULL DEFAULT 0,\n  \"total_amount\" bigint NOT NULL,\n  \"commission_amount\" bigint NOT NULL DEFAULT 0,\n  \"deposit_amount\" bigint NOT NULL,\n  \"deposit_due_at\" timestamptz,\n  \"balance_due_at\" timestamptz,\n  \"cancellation_policy_id\" bigint,\n  \"policy_snapshot\" jsonb,\n  \"status\" varchar(32) NOT NULL,\n  \"cancelled_at\" timestamptz,\n  \"refund_amount\" bigint,\n  \"cancellation_snapshot\" jsonb,\n  \"notes\" text,\n  \"is_active\" boolean NOT NULL DEFAULT true,\n  \"created_by\" bigint NOT NULL,\n  \"updated_by\" bigint NOT NULL,\n  \"created_at\" timestamptz NOT NULL DEFAULT now(),\n  \"updated_at\" timestamptz NOT NULL DEFAULT now()\n)");
    await queryRunner.query("CREATE TABLE \"rental_payments\" (\n  \"id\" BIGSERIAL PRIMARY KEY NOT NULL,\n  \"property_id\" bigint NOT NULL,\n  \"reservation_id\" bigint NOT NULL,\n  \"type\" varchar(16) NOT NULL,\n  \"amount\" bigint NOT NULL,\n  \"occurred_on\" date NOT NULL,\n  \"method\" varchar(100),\n  \"reference\" varchar(255),\n  \"notes\" text,\n  \"status\" varchar(16) NOT NULL,\n  \"created_by\" bigint NOT NULL,\n  \"updated_by\" bigint NOT NULL,\n  \"created_at\" timestamptz NOT NULL DEFAULT now(),\n  \"updated_at\" timestamptz NOT NULL DEFAULT now()\n)");
    await queryRunner.query("CREATE TABLE \"rental_expenses\" (\n  \"id\" BIGSERIAL PRIMARY KEY NOT NULL,\n  \"property_id\" bigint NOT NULL,\n  \"reservation_id\" bigint,\n  \"name\" varchar(255) NOT NULL,\n  \"category\" varchar(100),\n  \"amount\" bigint NOT NULL,\n  \"incurred_on\" date NOT NULL,\n  \"paid_on\" date,\n  \"status\" varchar(16) NOT NULL,\n  \"notes\" text,\n  \"created_by\" bigint NOT NULL,\n  \"updated_by\" bigint NOT NULL,\n  \"created_at\" timestamptz NOT NULL DEFAULT now(),\n  \"updated_at\" timestamptz NOT NULL DEFAULT now()\n)");
    await queryRunner.query("CREATE TABLE \"rental_blocks\" (\n  \"id\" BIGSERIAL PRIMARY KEY NOT NULL,\n  \"property_id\" bigint NOT NULL,\n  \"starts_at\" timestamptz NOT NULL,\n  \"ends_at\" timestamptz NOT NULL,\n  \"reason\" varchar(255) NOT NULL,\n  \"notes\" text,\n  \"is_active\" boolean NOT NULL DEFAULT true,\n  \"created_by\" bigint NOT NULL,\n  \"updated_by\" bigint NOT NULL,\n  \"created_at\" timestamptz NOT NULL DEFAULT now(),\n  \"updated_at\" timestamptz NOT NULL DEFAULT now()\n)");
    await queryRunner.query("CREATE TABLE \"rental_turnovers\" (\n  \"id\" BIGSERIAL PRIMARY KEY NOT NULL,\n  \"property_id\" bigint NOT NULL,\n  \"incoming_reservation_id\" bigint NOT NULL,\n  \"previous_reservation_id\" bigint,\n  \"linen_ready\" boolean,\n  \"cleaning_status\" varchar(16) NOT NULL,\n  \"planned_ready_at\" timestamptz,\n  \"ready_at\" timestamptz,\n  \"same_day_approved_at\" timestamptz,\n  \"notes\" text,\n  \"created_by\" bigint NOT NULL,\n  \"updated_by\" bigint NOT NULL,\n  \"created_at\" timestamptz NOT NULL DEFAULT now(),\n  \"updated_at\" timestamptz NOT NULL DEFAULT now()\n)");
    await queryRunner.query("CREATE TABLE \"rental_audit_events\" (\n  \"id\" BIGSERIAL PRIMARY KEY NOT NULL,\n  \"property_id\" bigint NOT NULL,\n  \"actor_id\" bigint NOT NULL,\n  \"action\" varchar(100) NOT NULL,\n  \"resource_type\" varchar(64) NOT NULL,\n  \"resource_id\" bigint NOT NULL,\n  \"changes\" jsonb NOT NULL,\n  \"created_at\" timestamptz NOT NULL DEFAULT now()\n)");
    await queryRunner.query("CREATE TABLE \"rental_operations\" (\n  \"id\" BIGSERIAL PRIMARY KEY NOT NULL,\n  \"property_id\" bigint NOT NULL,\n  \"actor_id\" bigint NOT NULL,\n  \"request_key\" uuid NOT NULL,\n  \"operation\" varchar(100) NOT NULL,\n  \"request_hash\" char(64) NOT NULL,\n  \"response\" jsonb NOT NULL,\n  \"created_at\" timestamptz NOT NULL DEFAULT now()\n)");
    await queryRunner.query("CREATE INDEX \"idx_rental_properties_owner\" ON \"rental_properties\" (\"owner_id\")");
    await queryRunner.query("CREATE UNIQUE INDEX \"uq_rental_collaborator\" ON \"rental_collaborators\" (\"property_id\", \"user_id\")");
    await queryRunner.query("CREATE INDEX \"idx_rental_collaborator_access\" ON \"rental_collaborators\" (\"user_id\", \"is_active\", \"property_id\")");
    await queryRunner.query("CREATE UNIQUE INDEX \"uq_rental_policy_property_id\" ON \"rental_cancellation_policies\" (\"property_id\", \"id\")");
    await queryRunner.query("CREATE INDEX \"idx_rental_policy_listing\" ON \"rental_cancellation_policies\" (\"property_id\", \"is_active\", \"id\")");
    await queryRunner.query("CREATE UNIQUE INDEX \"uq_rental_policy_threshold\" ON \"rental_cancellation_rules\" (\"policy_id\", \"min_days_before\")");
    await queryRunner.query("CREATE UNIQUE INDEX \"uq_rental_reservation_property_id\" ON \"rental_reservations\" (\"property_id\", \"id\")");
    await queryRunner.query("CREATE INDEX \"idx_rental_reservation_calendar\" ON \"rental_reservations\" (\"property_id\", \"check_in_on\", \"id\")");
    await queryRunner.query("CREATE INDEX \"idx_rental_reservation_status\" ON \"rental_reservations\" (\"property_id\", \"status\", \"check_in_on\", \"id\")");
    await queryRunner.query("CREATE UNIQUE INDEX \"uq_rental_reservation_external_reference\" ON \"rental_reservations\" (\"property_id\", \"channel\", \"external_reference\")");
    await queryRunner.query("CREATE INDEX \"idx_rental_payment_balance\" ON \"rental_payments\" (\"property_id\", \"reservation_id\", \"type\", \"status\")");
    await queryRunner.query("CREATE INDEX \"idx_rental_payment_cash\" ON \"rental_payments\" (\"property_id\", \"occurred_on\", \"id\")");
    await queryRunner.query("CREATE INDEX \"idx_rental_expense_listing\" ON \"rental_expenses\" (\"property_id\", \"incurred_on\", \"id\")");
    await queryRunner.query("CREATE INDEX \"idx_rental_expense_cash\" ON \"rental_expenses\" (\"property_id\", \"status\", \"paid_on\", \"id\")");
    await queryRunner.query("CREATE INDEX \"idx_rental_expense_reservation\" ON \"rental_expenses\" (\"property_id\", \"reservation_id\")");
    await queryRunner.query("CREATE INDEX \"idx_rental_block_calendar\" ON \"rental_blocks\" (\"property_id\", \"is_active\", \"starts_at\", \"id\")");
    await queryRunner.query("CREATE UNIQUE INDEX \"uq_rental_turnover_incoming\" ON \"rental_turnovers\" (\"incoming_reservation_id\")");
    await queryRunner.query("CREATE INDEX \"idx_rental_turnover_listing\" ON \"rental_turnovers\" (\"property_id\", \"planned_ready_at\", \"id\")");
    await queryRunner.query("CREATE INDEX \"idx_rental_turnover_previous\" ON \"rental_turnovers\" (\"property_id\", \"previous_reservation_id\")");
    await queryRunner.query("CREATE INDEX \"idx_rental_audit_history\" ON \"rental_audit_events\" (\"property_id\", \"created_at\", \"id\")");
    await queryRunner.query("CREATE INDEX \"idx_rental_audit_resource\" ON \"rental_audit_events\" (\"property_id\", \"resource_type\", \"resource_id\", \"id\")");
    await queryRunner.query("CREATE UNIQUE INDEX \"uq_rental_operation_request\" ON \"rental_operations\" (\"property_id\", \"actor_id\", \"request_key\")");
    await queryRunner.query("ALTER TABLE \"rental_properties\" ADD CONSTRAINT \"fk_rental_properties_owner_id\" FOREIGN KEY (\"owner_id\") REFERENCES \"users\" (\"id\") ON DELETE RESTRICT");
    await queryRunner.query("ALTER TABLE \"rental_properties\" ADD CONSTRAINT \"fk_rental_properties_created_by\" FOREIGN KEY (\"created_by\") REFERENCES \"users\" (\"id\") ON DELETE RESTRICT");
    await queryRunner.query("ALTER TABLE \"rental_properties\" ADD CONSTRAINT \"fk_rental_properties_updated_by\" FOREIGN KEY (\"updated_by\") REFERENCES \"users\" (\"id\") ON DELETE RESTRICT");
    await queryRunner.query("ALTER TABLE \"rental_properties\" ADD CONSTRAINT \"fk_rental_properties_id_default_cancellation_policy_id\" FOREIGN KEY (\"id\", \"default_cancellation_policy_id\") REFERENCES \"rental_cancellation_policies\" (\"property_id\", \"id\") ON DELETE RESTRICT");
    await queryRunner.query("ALTER TABLE \"rental_collaborators\" ADD CONSTRAINT \"fk_rental_collaborators_property_id\" FOREIGN KEY (\"property_id\") REFERENCES \"rental_properties\" (\"id\") ON DELETE RESTRICT");
    await queryRunner.query("ALTER TABLE \"rental_collaborators\" ADD CONSTRAINT \"fk_rental_collaborators_user_id\" FOREIGN KEY (\"user_id\") REFERENCES \"users\" (\"id\") ON DELETE RESTRICT");
    await queryRunner.query("ALTER TABLE \"rental_collaborators\" ADD CONSTRAINT \"fk_rental_collaborators_created_by\" FOREIGN KEY (\"created_by\") REFERENCES \"users\" (\"id\") ON DELETE RESTRICT");
    await queryRunner.query("ALTER TABLE \"rental_collaborators\" ADD CONSTRAINT \"fk_rental_collaborators_updated_by\" FOREIGN KEY (\"updated_by\") REFERENCES \"users\" (\"id\") ON DELETE RESTRICT");
    await queryRunner.query("ALTER TABLE \"rental_cancellation_policies\" ADD CONSTRAINT \"fk_rental_cancellation_policies_property_id\" FOREIGN KEY (\"property_id\") REFERENCES \"rental_properties\" (\"id\") ON DELETE RESTRICT");
    await queryRunner.query("ALTER TABLE \"rental_cancellation_policies\" ADD CONSTRAINT \"fk_rental_cancellation_policies_created_by\" FOREIGN KEY (\"created_by\") REFERENCES \"users\" (\"id\") ON DELETE RESTRICT");
    await queryRunner.query("ALTER TABLE \"rental_cancellation_policies\" ADD CONSTRAINT \"fk_rental_cancellation_policies_updated_by\" FOREIGN KEY (\"updated_by\") REFERENCES \"users\" (\"id\") ON DELETE RESTRICT");
    await queryRunner.query("ALTER TABLE \"rental_cancellation_rules\" ADD CONSTRAINT \"fk_rental_cancellation_rules_policy_id\" FOREIGN KEY (\"policy_id\") REFERENCES \"rental_cancellation_policies\" (\"id\") ON DELETE RESTRICT");
    await queryRunner.query("ALTER TABLE \"rental_cancellation_rules\" ADD CONSTRAINT \"fk_rental_cancellation_rules_created_by\" FOREIGN KEY (\"created_by\") REFERENCES \"users\" (\"id\") ON DELETE RESTRICT");
    await queryRunner.query("ALTER TABLE \"rental_cancellation_rules\" ADD CONSTRAINT \"fk_rental_cancellation_rules_updated_by\" FOREIGN KEY (\"updated_by\") REFERENCES \"users\" (\"id\") ON DELETE RESTRICT");
    await queryRunner.query("ALTER TABLE \"rental_reservations\" ADD CONSTRAINT \"fk_rental_reservations_property_id\" FOREIGN KEY (\"property_id\") REFERENCES \"rental_properties\" (\"id\") ON DELETE RESTRICT");
    await queryRunner.query("ALTER TABLE \"rental_reservations\" ADD CONSTRAINT \"fk_rental_reservations_property_id_cancellation_policy_id\" FOREIGN KEY (\"property_id\", \"cancellation_policy_id\") REFERENCES \"rental_cancellation_policies\" (\"property_id\", \"id\") ON DELETE RESTRICT");
    await queryRunner.query("ALTER TABLE \"rental_reservations\" ADD CONSTRAINT \"fk_rental_reservations_created_by\" FOREIGN KEY (\"created_by\") REFERENCES \"users\" (\"id\") ON DELETE RESTRICT");
    await queryRunner.query("ALTER TABLE \"rental_reservations\" ADD CONSTRAINT \"fk_rental_reservations_updated_by\" FOREIGN KEY (\"updated_by\") REFERENCES \"users\" (\"id\") ON DELETE RESTRICT");
    await queryRunner.query("ALTER TABLE \"rental_payments\" ADD CONSTRAINT \"fk_rental_payments_property_id\" FOREIGN KEY (\"property_id\") REFERENCES \"rental_properties\" (\"id\") ON DELETE RESTRICT");
    await queryRunner.query("ALTER TABLE \"rental_payments\" ADD CONSTRAINT \"fk_rental_payments_property_id_reservation_id\" FOREIGN KEY (\"property_id\", \"reservation_id\") REFERENCES \"rental_reservations\" (\"property_id\", \"id\") ON DELETE RESTRICT");
    await queryRunner.query("ALTER TABLE \"rental_payments\" ADD CONSTRAINT \"fk_rental_payments_created_by\" FOREIGN KEY (\"created_by\") REFERENCES \"users\" (\"id\") ON DELETE RESTRICT");
    await queryRunner.query("ALTER TABLE \"rental_payments\" ADD CONSTRAINT \"fk_rental_payments_updated_by\" FOREIGN KEY (\"updated_by\") REFERENCES \"users\" (\"id\") ON DELETE RESTRICT");
    await queryRunner.query("ALTER TABLE \"rental_expenses\" ADD CONSTRAINT \"fk_rental_expenses_property_id\" FOREIGN KEY (\"property_id\") REFERENCES \"rental_properties\" (\"id\") ON DELETE RESTRICT");
    await queryRunner.query("ALTER TABLE \"rental_expenses\" ADD CONSTRAINT \"fk_rental_expenses_property_id_reservation_id\" FOREIGN KEY (\"property_id\", \"reservation_id\") REFERENCES \"rental_reservations\" (\"property_id\", \"id\") ON DELETE RESTRICT");
    await queryRunner.query("ALTER TABLE \"rental_expenses\" ADD CONSTRAINT \"fk_rental_expenses_created_by\" FOREIGN KEY (\"created_by\") REFERENCES \"users\" (\"id\") ON DELETE RESTRICT");
    await queryRunner.query("ALTER TABLE \"rental_expenses\" ADD CONSTRAINT \"fk_rental_expenses_updated_by\" FOREIGN KEY (\"updated_by\") REFERENCES \"users\" (\"id\") ON DELETE RESTRICT");
    await queryRunner.query("ALTER TABLE \"rental_blocks\" ADD CONSTRAINT \"fk_rental_blocks_property_id\" FOREIGN KEY (\"property_id\") REFERENCES \"rental_properties\" (\"id\") ON DELETE RESTRICT");
    await queryRunner.query("ALTER TABLE \"rental_blocks\" ADD CONSTRAINT \"fk_rental_blocks_created_by\" FOREIGN KEY (\"created_by\") REFERENCES \"users\" (\"id\") ON DELETE RESTRICT");
    await queryRunner.query("ALTER TABLE \"rental_blocks\" ADD CONSTRAINT \"fk_rental_blocks_updated_by\" FOREIGN KEY (\"updated_by\") REFERENCES \"users\" (\"id\") ON DELETE RESTRICT");
    await queryRunner.query("ALTER TABLE \"rental_turnovers\" ADD CONSTRAINT \"fk_rental_turnovers_property_id\" FOREIGN KEY (\"property_id\") REFERENCES \"rental_properties\" (\"id\") ON DELETE RESTRICT");
    await queryRunner.query("ALTER TABLE \"rental_turnovers\" ADD CONSTRAINT \"fk_rental_turnovers_property_id_incoming_reservation_id\" FOREIGN KEY (\"property_id\", \"incoming_reservation_id\") REFERENCES \"rental_reservations\" (\"property_id\", \"id\") ON DELETE RESTRICT");
    await queryRunner.query("ALTER TABLE \"rental_turnovers\" ADD CONSTRAINT \"fk_rental_turnovers_property_id_previous_reservation_id\" FOREIGN KEY (\"property_id\", \"previous_reservation_id\") REFERENCES \"rental_reservations\" (\"property_id\", \"id\") ON DELETE RESTRICT");
    await queryRunner.query("ALTER TABLE \"rental_turnovers\" ADD CONSTRAINT \"fk_rental_turnovers_created_by\" FOREIGN KEY (\"created_by\") REFERENCES \"users\" (\"id\") ON DELETE RESTRICT");
    await queryRunner.query("ALTER TABLE \"rental_turnovers\" ADD CONSTRAINT \"fk_rental_turnovers_updated_by\" FOREIGN KEY (\"updated_by\") REFERENCES \"users\" (\"id\") ON DELETE RESTRICT");
    await queryRunner.query("ALTER TABLE \"rental_audit_events\" ADD CONSTRAINT \"fk_rental_audit_events_property_id\" FOREIGN KEY (\"property_id\") REFERENCES \"rental_properties\" (\"id\") ON DELETE RESTRICT");
    await queryRunner.query("ALTER TABLE \"rental_audit_events\" ADD CONSTRAINT \"fk_rental_audit_events_actor_id\" FOREIGN KEY (\"actor_id\") REFERENCES \"users\" (\"id\") ON DELETE RESTRICT");
    await queryRunner.query("ALTER TABLE \"rental_operations\" ADD CONSTRAINT \"fk_rental_operations_property_id\" FOREIGN KEY (\"property_id\") REFERENCES \"rental_properties\" (\"id\") ON DELETE RESTRICT");
    await queryRunner.query("ALTER TABLE \"rental_operations\" ADD CONSTRAINT \"fk_rental_operations_actor_id\" FOREIGN KEY (\"actor_id\") REFERENCES \"users\" (\"id\") ON DELETE RESTRICT");
    await queryRunner.query("ALTER TABLE \"rental_properties\" ADD CONSTRAINT \"ck_rental_properties_max_guests\" CHECK (max_guests > 0)");
    await queryRunner.query("ALTER TABLE \"rental_properties\" ADD CONSTRAINT \"ck_rental_properties_default_nightly_rate\" CHECK (default_nightly_rate > 0)");
    await queryRunner.query("ALTER TABLE \"rental_properties\" ADD CONSTRAINT \"ck_rental_properties_default_deposit_percent\" CHECK (default_deposit_percent BETWEEN 0 AND 100)");
    await queryRunner.query("ALTER TABLE \"rental_properties\" ADD CONSTRAINT \"ck_rental_properties_minimum_turnover_minutes\" CHECK (minimum_turnover_minutes >= 0)");
    await queryRunner.query("ALTER TABLE \"rental_cancellation_rules\" ADD CONSTRAINT \"ck_rental_cancellation_rules_min_days_before\" CHECK (min_days_before >= 0)");
    await queryRunner.query("ALTER TABLE \"rental_cancellation_rules\" ADD CONSTRAINT \"ck_rental_cancellation_rules_refund_percent\" CHECK (refund_percent BETWEEN 0 AND 100)");
    await queryRunner.query("ALTER TABLE \"rental_reservations\" ADD CONSTRAINT \"ck_rental_reservations_guests_count\" CHECK (guests_count > 0)");
    await queryRunner.query("ALTER TABLE \"rental_reservations\" ADD CONSTRAINT \"ck_rental_reservations_channel\" CHECK (channel IN ('whatsapp', 'airbnb', 'facebook', 'other'))");
    await queryRunner.query("ALTER TABLE \"rental_reservations\" ADD CONSTRAINT \"ck_rental_reservations_check_out_on\" CHECK (check_out_on > check_in_on)");
    await queryRunner.query("ALTER TABLE \"rental_reservations\" ADD CONSTRAINT \"ck_rental_reservations_nightly_rate\" CHECK (nightly_rate > 0)");
    await queryRunner.query("ALTER TABLE \"rental_reservations\" ADD CONSTRAINT \"ck_rental_reservations_cleaning_fee\" CHECK (cleaning_fee >= 0)");
    await queryRunner.query("ALTER TABLE \"rental_reservations\" ADD CONSTRAINT \"ck_rental_reservations_discount_amount\" CHECK (discount_amount >= 0)");
    await queryRunner.query("ALTER TABLE \"rental_reservations\" ADD CONSTRAINT \"ck_rental_reservations_total_amount\" CHECK (total_amount > 0)");
    await queryRunner.query("ALTER TABLE \"rental_reservations\" ADD CONSTRAINT \"ck_rental_reservations_commission_amount\" CHECK (commission_amount >= 0 AND commission_amount <= total_amount)");
    await queryRunner.query("ALTER TABLE \"rental_reservations\" ADD CONSTRAINT \"ck_rental_reservations_deposit_amount\" CHECK (deposit_amount >= 0 AND deposit_amount <= total_amount)");
    await queryRunner.query("ALTER TABLE \"rental_reservations\" ADD CONSTRAINT \"ck_rental_reservations_status\" CHECK (status IN ('draft', 'confirmed', 'in_progress', 'completed', 'cancelled'))");
    await queryRunner.query("ALTER TABLE \"rental_reservations\" ADD CONSTRAINT \"ck_rental_reservations_refund_amount\" CHECK (refund_amount >= 0)");
    await queryRunner.query("ALTER TABLE \"rental_reservations\" ADD CONSTRAINT \"ck_rental_reservations_total_formula\" CHECK (\"total_amount\"::numeric = (\"check_out_on\" - \"check_in_on\")::numeric * \"nightly_rate\"::numeric + \"cleaning_fee\"::numeric - \"discount_amount\"::numeric)");
    await queryRunner.query("ALTER TABLE \"rental_reservations\" ADD CONSTRAINT \"ck_rental_reservations_cancellation\" CHECK ((\"status\" = 'cancelled' AND \"cancelled_at\" IS NOT NULL AND \"refund_amount\" IS NOT NULL AND \"cancellation_snapshot\" IS NOT NULL) OR (\"status\" <> 'cancelled' AND \"cancelled_at\" IS NULL AND \"refund_amount\" IS NULL AND \"cancellation_snapshot\" IS NULL))");
    await queryRunner.query("ALTER TABLE \"rental_payments\" ADD CONSTRAINT \"ck_rental_payments_type\" CHECK (type IN ('payment', 'refund'))");
    await queryRunner.query("ALTER TABLE \"rental_payments\" ADD CONSTRAINT \"ck_rental_payments_amount\" CHECK (amount > 0)");
    await queryRunner.query("ALTER TABLE \"rental_payments\" ADD CONSTRAINT \"ck_rental_payments_status\" CHECK (status IN ('confirmed', 'voided'))");
    await queryRunner.query("ALTER TABLE \"rental_expenses\" ADD CONSTRAINT \"ck_rental_expenses_amount\" CHECK (amount > 0)");
    await queryRunner.query("ALTER TABLE \"rental_expenses\" ADD CONSTRAINT \"ck_rental_expenses_status\" CHECK (status IN ('pending', 'paid', 'voided'))");
    await queryRunner.query("ALTER TABLE \"rental_expenses\" ADD CONSTRAINT \"ck_rental_expenses_paid_date\" CHECK ((\"status\" = 'paid' AND \"paid_on\" IS NOT NULL AND \"paid_on\" >= \"incurred_on\") OR (\"status\" <> 'paid' AND \"paid_on\" IS NULL))");
    await queryRunner.query("ALTER TABLE \"rental_blocks\" ADD CONSTRAINT \"ck_rental_blocks_ends_at\" CHECK (ends_at > starts_at)");
    await queryRunner.query("ALTER TABLE \"rental_turnovers\" ADD CONSTRAINT \"ck_rental_turnovers_previous_reservation_id\" CHECK (previous_reservation_id <> incoming_reservation_id)");
    await queryRunner.query("ALTER TABLE \"rental_turnovers\" ADD CONSTRAINT \"ck_rental_turnovers_cleaning_status\" CHECK (cleaning_status IN ('pending', 'in_progress', 'completed'))");
    await queryRunner.query("ALTER TABLE \"rental_turnovers\" ADD CONSTRAINT \"ck_rental_turnovers_readiness\" CHECK (\"ready_at\" IS NULL OR (\"linen_ready\" IS TRUE AND \"cleaning_status\" = 'completed'))");
  }
  async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('ALTER TABLE "rental_properties" DROP CONSTRAINT "fk_rental_properties_id_default_cancellation_policy_id"');
    await queryRunner.query('DROP TABLE "rental_operations"');
    await queryRunner.query('DROP TABLE "rental_audit_events"');
    await queryRunner.query('DROP TABLE "rental_turnovers"');
    await queryRunner.query('DROP TABLE "rental_blocks"');
    await queryRunner.query('DROP TABLE "rental_expenses"');
    await queryRunner.query('DROP TABLE "rental_payments"');
    await queryRunner.query('DROP TABLE "rental_reservations"');
    await queryRunner.query('DROP TABLE "rental_cancellation_rules"');
    await queryRunner.query('DROP TABLE "rental_cancellation_policies"');
    await queryRunner.query('DROP TABLE "rental_collaborators"');
    await queryRunner.query('DROP TABLE "rental_properties"');
  }
}
