import { act, render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { beforeEach, afterEach, expect, it, vi } from "vitest";
import { MemoryRouter } from "react-router";
import { createTheme, ThemeProvider } from "@mui/material/styles";
import { sileo } from "sileo";
import MobileBottomNav from "../../../../layouts/components/MobileBottomNav";
import useAuthStore from "../../../../store/authStore";
import settings from "../../../../store/generalSettings/generalSettingsStore";
import { createMobilePreferences, mobileStorageKey, useMobileNavigationStore as store } from "../../../../store/mobileNavigationStore";
import { groups, reference } from "./fixtures";
import i18n from "../../../../translate";
const context = vi.hoisted(() => ({ isFetching: false, isError: false, refetch: vi.fn() }));
vi.mock("../../../../services/authorizationService", () => ({ useAuthorizationContext: () => context }));
vi.mock("sileo", () => ({ sileo: { success: vi.fn(), error: vi.fn() } }));
const label = (key: string) => i18n.t(`layout:mobile_nav.${key}`);
const setup = () => render(<ThemeProvider theme={createTheme()}><MemoryRouter><MobileBottomNav /></MemoryRouter></ThemeProvider>);
beforeEach(() => {
  vi.clearAllMocks(); context.isFetching = false; context.isError = false;
  useAuthStore.getState().logout();
  useAuthStore.getState().login({ token: "synthetic", expiresAt: Date.now() + 900_000, user: { id: "a", name: "A" } });
  settings.getState().setContext({ roles: [], actions: [], modules: groups });
  store.getState().hydrate(null);
});
afterEach(() => { vi.restoreAllMocks(); vi.unstubAllGlobals(); });
it("has exactly four editable slots and a fixed home; locking removes empty controls from focus", async () => {
  setup();
  expect(screen.getAllByRole("button", { name: /Agregar acceso:/ })).toHaveLength(4);
  expect(screen.getByRole("link", { name: label("home") })).toHaveAttribute("href", "/");
  await userEvent.click(screen.getByRole("button", { name: label("lock") }));
  expect(screen.queryByRole("button", { name: /Agregar acceso:/ })).not.toBeInTheDocument();
  expect(screen.getAllByRole("link")).toHaveLength(1);
  expect(JSON.parse(localStorage.getItem(mobileStorageKey("a"))!).locked).toBe(true);
  expect(sileo.success).toHaveBeenCalledTimes(1);
});
it("adds a current authorized section, excludes duplicate slots, links to the exact route and allows removal", async () => {
  setup();
  await userEvent.click(screen.getAllByRole("button", { name: /Agregar acceso:/ })[0]);
  await userEvent.click(screen.getByRole("radio", { name: "Reservas" }));
  await userEvent.click(screen.getByRole("button", { name: i18n.t("core:save") }));
  await waitFor(() => expect(screen.queryByRole("dialog")).not.toBeInTheDocument());
  await userEvent.click(screen.getAllByRole("button", { name: /Agregar acceso:/ })[0]);
  expect(screen.getByRole("radio", { name: /Reservas/ })).toBeDisabled();
  await userEvent.keyboard("{Escape}");
  await waitFor(() => expect(screen.queryByRole("dialog")).not.toBeInTheDocument());
  await userEvent.click(screen.getByRole("button", { name: label("lock") }));
  expect(screen.getByRole("link", { name: i18n.t("layout:mobile_nav.go", { section: "Reservas" }) })).toHaveAttribute("href", "/tools/reservations");
  await userEvent.click(screen.getByRole("button", { name: label("unlock") }));
  await userEvent.click(screen.getByRole("button", { name: /Editar acceso:.*Reservas/ }));
  await userEvent.click(screen.getByRole("button", { name: label("remove") }));
  expect(store.getState().preferences.slots[0]).toBeNull();
});
it("keeps the modal and selected section after a failed write, allowing retry", async () => {
  setup();
  await userEvent.click(screen.getAllByRole("button", { name: /Agregar acceso:/ })[0]);
  await userEvent.click(screen.getByRole("radio", { name: "Reservas" }));
  const write = vi.spyOn(Storage.prototype, "setItem").mockImplementation(() => { throw new Error("blocked"); });
  await userEvent.click(screen.getByRole("button", { name: i18n.t("core:save") }));
  expect(screen.getByRole("dialog")).toBeInTheDocument();
  expect(screen.getByRole("radio", { name: "Reservas" })).toHaveAttribute("aria-checked", "true");
  expect(screen.getByRole("alert")).toHaveTextContent(label("storage_error"));
  expect(store.getState().preferences.slots[0]).toBeNull();
  expect(sileo.success).not.toHaveBeenCalled(); expect(sileo.error).toHaveBeenCalled();
  write.mockRestore();
  await userEvent.click(screen.getByRole("button", { name: i18n.t("core:save") }));
  await waitFor(() => expect(screen.queryByRole("dialog")).not.toBeInTheDocument());
});
it("blocks a revoked shortcut and preserves its reference for replacement", () => {
  localStorage.setItem(mobileStorageKey("a"), JSON.stringify({ ...createMobilePreferences(), locked: true, slots: [reference, null, null, null] }));
  setup();
  act(() => settings.getState().setContext({ roles: [], actions: [], modules: [] }));
  expect(screen.getByRole("button", { name: label("unavailable") })).toBeDisabled();
  expect(screen.getAllByRole("link")).toHaveLength(1);
  expect(store.getState().preferences.slots[0]).toEqual(reference);
});
it("distinguishes permission errors from empty sections and offers retry", async () => {
  context.isError = true;
  setup();
  await userEvent.click(screen.getAllByRole("button", { name: /Agregar acceso:/ })[0]);
  expect(screen.getByRole("alert")).toHaveTextContent(i18n.t("core:auth_context_error_message"));
  expect(screen.queryByText(label("empty"))).not.toBeInTheDocument();
  await userEvent.click(screen.getByRole("button", { name: i18n.t("core:retry") }));
  expect(context.refetch).toHaveBeenCalledTimes(1);
  expect(screen.getByRole("button", { name: i18n.t("core:save") })).toBeDisabled();
});
it("closes the editor across identity changes and hides navigation while the virtual keyboard is active", async () => {
  vi.stubGlobal("visualViewport", { height: window.innerHeight - 200, addEventListener: vi.fn(), removeEventListener: vi.fn() });
  setup();
  await userEvent.click(screen.getAllByRole("button", { name: /Agregar acceso:/ })[0]);
  await userEvent.click(screen.getByPlaceholderText(label("search")));
  expect(screen.getByTestId("mobile-bottom-nav")).not.toBeVisible();
  act(() => useAuthStore.getState().login({ token: "synthetic-b", expiresAt: Date.now() + 900_000, user: { id: "b", name: "B" } }));
  await waitFor(() => expect(screen.queryByRole("dialog")).not.toBeInTheDocument());
  expect(store.getState().ownerId).toBe("b");
  expect(store.getState().preferences.slots).toEqual([null, null, null, null]);
});
