/** Translation handoff owned by the booking lane; merged into the rental namespace. */
export const bookingCopy = {
  guest_name: ["Nombre del huésped", "Guest name"],
  guest_contact: ["Contacto del huésped", "Guest contact"],
  guests_count: ["Cantidad de huéspedes", "Guest count"],
  external_reference: ["Referencia externa", "External reference"],
  channel: ["Canal", "Channel"],
  check_in_on: ["Fecha de entrada", "Check-in date"],
  check_out_on: ["Fecha de salida", "Check-out date"],
  check_in_time: ["Hora de entrada", "Check-in time"],
  check_out_time: ["Hora de salida", "Check-out time"],
  nightly_rate: ["Tarifa por noche (CLP)", "Nightly rate (CLP)"],
  cleaning_fee: ["Limpieza (CLP)", "Cleaning fee (CLP)"],
  discount_amount: ["Descuento (CLP)", "Discount (CLP)"],
  commission_amount: ["Comisión (CLP)", "Commission (CLP)"],
  deposit_amount: ["Abono acordado (CLP)", "Agreed deposit (CLP)"],
  deposit_due_at: ["Vencimiento del abono", "Deposit due at"],
  balance_due_at: ["Vencimiento del saldo", "Balance due at"],
  cancellation_policy: ["Política de cancelación", "Cancellation policy"],
  notes: ["Notas", "Notes"],
  active: ["Activo", "Active"],
  inactive: ["Archivado", "Archived"],
  all: ["Todos", "All"],
  archive_filter: ["Archivo", "Archive"],
  status: ["Estado", "Status"],
  from_on: ["Desde", "From"],
  to_on: ["Hasta (exclusivo)", "Until (exclusive)"],
  search_by: ["Buscar por", "Search by"],
  paired_period: [
    "Completa ambas fechas y usa un período válido de hasta 366 días.",
    "Enter both dates and a valid period of up to 366 days.",
  ],
  stay: ["Estadía", "Stay"],
  nights: ["Noches", "Nights"],
  nights_count: ["{{count}} noches", "{{count}} nights"],
  balance_due_amount: ["Saldo pendiente", "Balance due"],
  refund_due_amount: ["Devolución pendiente", "Refund due"],
  total_amount: ["Total acordado", "Agreed total"],
  expected_amount: [
    "Total esperado después de comisión",
    "Expected total after commission",
  ],
  received_amount: ["Cobrado", "Received"],
  refunded_amount: ["Devuelto", "Refunded"],
  new_reservation: ["Nueva reserva", "New reservation"],
  edit_reservation: ["Editar reserva", "Edit reservation"],
  reservation_detail: ["Ficha de reserva", "Reservation details"],
  open_detail: ["Abrir ficha", "Open details"],
  edit: ["Editar", "Edit"],
  close: ["Cerrar", "Close"],
  save: ["Guardar", "Save"],
  retry: ["Reintentar", "Retry"],
  load_error: [
    "No se pudo cargar la información. Reintenta.",
    "Could not load data. Try again.",
  ],
  quote_explanation: [
    "Una cotización no ocupa fechas. Se cobra por noches con horarios en {{timezone}}.",
    "A quote does not hold dates. Charges use nights and times in {{timezone}}.",
  ],
  agreement_locked: [
    "El acuerdo está congelado por confirmación o historial monetario. Puedes modificar contacto, notas y archivo.",
    "Confirmation or money history has frozen the agreement. Contact, notes and archive can still be edited.",
  ],
  history_unavailable: [
    "No se pudo verificar el historial monetario. Los campos comerciales permanecen protegidos.",
    "Money history could not be verified. Commercial fields remain protected.",
  ],
  apply_house_suggestions: [
    "Aplicar sugerencias configuradas de la casa",
    "Apply configured house suggestions",
  ],
  quote_total: [
    "{{nights}} noches · Total estimado {{amount}}",
    "{{nights}} nights · Estimated total {{amount}}",
  ],
  instant_with_offset: [
    "Usa fecha y hora ISO con zona explícita, por ejemplo 2026-10-01T15:00:00-03:00.",
    "Use an ISO date and time with an explicit offset, for example 2026-10-01T15:00:00-03:00.",
  ],
  archive_occupancy_explanation: [
    "Archivar conserva el historial y no libera fechas de una estadía confirmada, iniciada o completada. Para liberar fechas corresponde cancelar cuando esté permitido.",
    "Archiving preserves history and occupied dates of confirmed, started or completed stays. Cancel when permitted to release dates.",
  ],
  confirm_reservation: ["Confirmar reserva", "Confirm reservation"],
  cancel_reservation: ["Cancelar reserva", "Cancel reservation"],
  start_stay: ["Registrar entrada", "Start stay"],
  complete_stay: ["Registrar salida", "Complete stay"],
  payments_and_refunds: ["Cobros y devoluciones", "Payments and refunds"],
  frozen_policy: [
    "Condiciones conservadas del acuerdo",
    "Frozen agreement conditions",
  ],
  policy_rule_summary: [
    "Desde {{days}} días de anticipación: devolución {{percent}}%",
    "From {{days}} days before: {{percent}}% refund",
  ],
  cancellation_record_summary: [
    "Cancelación registrada con {{days}} días de anticipación. Devolución aprobada: {{refund}}.",
    "Cancellation recorded {{days}} days before. Approved refund: {{refund}}.",
  ],
  not_recorded: ["Sin registrar", "Not recorded"],
  none: ["Ninguna", "None"],
  unknown: ["Por confirmar", "Unknown"],
  yes: ["Disponible", "Available"],
  no: ["No disponible", "Unavailable"],
  same_day_explanation: [
    "Revisa los recambios afectados. Tu consentimiento se envía junto a la confirmación y el servidor valida la transición completa.",
    "Review affected turnovers. Consent is sent with confirmation and the server validates the complete transition.",
  ],
  no_same_day_requirements: [
    "No hay revisiones de recambio del mismo día en esta consulta.",
    "No same-day turnover reviews in this check.",
  ],
  incoming_transition: [
    "Entrada de reserva #{{id}}",
    "Incoming reservation #{{id}}",
  ],
  previous_transition: [
    "Reserva anterior #{{id}}",
    "Previous reservation #{{id}}",
  ],
  unsaved: ["sin guardar", "unsaved"],
  prospective_plan_warning: [
    "La transición actual puede cambiar al confirmar. Revisa la hora prevista; el servidor decide su compatibilidad.",
    "The current transition may change upon confirmation. Review the planned time; the server determines compatibility.",
  ],
  review_preparation: ["Revisar preparación", "Review preparation"],
  consent_same_day: [
    "Apruebo el recambio del mismo día del plan #{{id}}",
    "I approve the same-day turnover for plan #{{id}}",
  ],
  approval_not_required: [
    "No requiere aprobación pendiente",
    "No pending approval required",
  ],
  save_draft_before_review: [
    "Guarda primero el borrador para revisar su preparación.",
    "Save the draft before reviewing its preparation.",
  ],
  availability_not_hold: [
    "La consulta de disponibilidad no retiene fechas. La confirmación valida conflictos y preparaciones de forma conjunta.",
    "Availability checks do not hold dates. Confirmation validates conflicts and turnovers together.",
  ],
  direct_deposit_required: [
    "Para confirmar una reserva directa registra la política, un abono mayor que cero y el cobro del abono acordado.",
    "To confirm a direct reservation, select a policy, agree a positive deposit and record its receipt.",
  ],
  availability_review: ["Revisión de disponibilidad", "Availability review"],
  occupancy_conflict: [
    "Existe ocupación incompatible: {{type}} #{{id}}.",
    "Conflicting occupancy: {{type}} #{{id}}.",
  ],
  resource_reservation: ["Reserva", "Reservation"],
  resource_block: ["Bloqueo", "Block"],
  refresh_availability: [
    "Actualizar revisión de disponibilidad",
    "Refresh availability review",
  ],
  platform_reference: [
    "Referencia de condiciones externas",
    "External conditions reference",
  ],
  platform_description: [
    "Condiciones externas de Airbnb",
    "External Airbnb conditions",
  ],
  platform_manual_explanation: [
    "Registra las condiciones de Airbnb manualmente. Esta acción no sincroniza ni cobra en la plataforma.",
    "Record Airbnb conditions manually. This action does not synchronize with or charge the platform.",
  ],
  cancelled_at: ["Momento de cancelación", "Cancellation time"],
  refund_amount: ["Importe de devolución (CLP)", "Refund amount (CLP)"],
  resolution_note: ["Resolución externa", "External resolution"],
  cancel_explanation: [
    "Primero revisa el cálculo. Cancelar libera fechas y autoriza una devolución; el movimiento real de dinero se registra después.",
    "Review the calculation first. Cancellation releases dates and approves a refund; record the actual transfer separately.",
  ],
  preview_cancellation: ["Calcular cancelación", "Preview cancellation"],
  approved_refund: ["Devolución aprobada", "Approved refund"],
  days_before: ["Días de anticipación", "Days before"],
  refund_due_after_cancellation: [
    "Devolución pendiente después de cancelar",
    "Refund due after cancellation",
  ],
  review_cancel_amount: [
    "He revisado las condiciones y el importe de devolución",
    "I have reviewed the conditions and refund amount",
  ],
  preview_needs_refresh: [
    "La revisión debe recalcularse antes de confirmar.",
    "Recalculate the preview before confirming.",
  ],
  start_requirements: [
    "La entrada requiere horario vigente, ropa disponible, limpieza completada y preparación real registrada. El servidor valida el estado al enviar.",
    "Starting requires the agreed time, available linen, completed cleaning and recorded actual readiness. The server validates state on submission.",
  ],
  complete_requirements: [
    "La salida se registra cuando se alcanza la hora acordada. El servidor verifica el horario.",
    "Completion can be recorded once the agreed checkout time is reached. The server verifies timing.",
  ],
  expired_unstarted_stay: [
    "Esta estadía venció sin registrar entrada. La versión actual no permite regularización retroactiva.",
    "This stay expired without a recorded start. The current version does not support retroactive adjustment.",
  ],
  actual_preparation_required: [
    "Completa y registra la preparación real antes de iniciar. Una aprobación futura no acredita limpieza realizada.",
    "Complete and record actual readiness before starting. Future approval does not prove completed cleaning.",
  ],
  reason: ["Motivo", "Reason"],
  starts_at: ["Inicio del bloqueo", "Block starts at"],
  ends_at: ["Fin del bloqueo", "Block ends at"],
  new_block: ["Nuevo bloqueo", "New block"],
  edit_block: ["Editar bloqueo", "Edit block"],
  block_explanation: [
    "Bloquea un intervalo de instantes; un bloqueo inactivo libera disponibilidad. Zona de la casa: {{timezone}}.",
    "Block an interval of instants; an inactive block releases availability. House timezone: {{timezone}}.",
  ],
  linen_ready: ["Recambio de ropa", "Linen readiness"],
  cleaning_status: ["Limpieza", "Cleaning"],
  planned_ready_at: ["Hora prevista de preparación", "Planned ready time"],
  ready_at: ["Hora real de preparación", "Actual ready time"],
  incoming_reservation_id: ["Reserva entrante", "Incoming reservation"],
  preparation: ["Preparación", "Preparation"],
  preparation_explanation: [
    "Registra recambio, limpieza y horas en {{timezone}}. La hora prevista no sustituye la preparación realizada.",
    "Record linen, cleaning and times in {{timezone}}. Planned readiness does not replace actual completion.",
  ],
  approval_required: [
    "Requiere aprobación del recambio del mismo día",
    "Same-day turnover approval required",
  ],
  preparation_changes_warning: [
    "Cambiar recambio, horario o vecino puede invalidar aprobaciones. Guarda primero el plan y revisa el estado actualizado.",
    "Changes to linen, timing or neighboring stays can invalidate approvals. Save the plan first and review its current state.",
  ],
  approve_saved_plan: [
    "Aprobar plan guardado del mismo día",
    "Approve saved same-day plan",
  ],
  open_reservation: ["Abrir reserva", "Open reservation"],
  previous_window: ["Período anterior", "Previous period"],
  next_window: ["Período siguiente", "Next period"],
  show_week: ["Ver semana", "Show week"],
  show_month: ["Ver mes", "Show month"],
  show_calendar: ["Ver calendario", "Show calendar"],
  show_agenda: ["Ver agenda", "Show agenda"],
  manage_blocks: ["Gestionar bloqueos", "Manage blocks"],
  include_non_occupying: [
    "Incluir cotizaciones y cancelaciones sin ocupación",
    "Include non-occupying quotes and cancellations",
  ],
  calendar_legend: [
    "Las tarjetas muestran noches ocupadas y horarios acordados. El archivo no libera ocupación; cotizaciones y cancelaciones se identifican por su estado. Usa la agenda para revisar todos los eventos.",
    "Cards show occupied nights and agreed times. Archiving does not release occupancy; quotes and cancellations show their status. Use the agenda to review all events.",
  ],
  calendar_window_error: [
    "No se pudo cargar el calendario completo. Reintenta o reduce el período.",
    "The complete calendar could not be loaded. Retry or reduce the period.",
  ],
  reduce_window: ["Reducir a una semana", "Reduce to one week"],
  empty_calendar: [
    "No hay reservas, bloqueos o preparaciones en este período.",
    "No reservations, blocks or turnovers in this period.",
  ],
  block: ["Bloqueo", "Block"],
  status_draft: ["Cotización", "Quote"],
  status_confirmed: ["Confirmada", "Confirmed"],
  status_in_progress: ["En estadía", "In progress"],
  status_completed: ["Completada", "Completed"],
  status_cancelled: ["Cancelada", "Cancelled"],
  channel_whatsapp: ["WhatsApp", "WhatsApp"],
  channel_airbnb: ["Airbnb", "Airbnb"],
  channel_facebook: ["Facebook", "Facebook"],
  channel_other: ["Otro", "Other"],
  cleaning_pending: ["Pendiente", "Pending"],
  cleaning_in_progress: ["En curso", "In progress"],
  cleaning_completed: ["Completada", "Completed"],
} as const;
